export const GET_ERRORS = 'GET_ERRORS';

// Authentication
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Reports
export const CREATE_WEEKLY_REPORT = 'CREATE_WEEKLY_REPORT';
export const CREATE_CUSTOM_REPORT = 'CREATE_CUSTOM_REPORT';
export const GET_WEEKLY_REPORT = 'GET_WEEKLY_REPORT';
export const GET_CUSTOM_REPORT = 'GET_CUSTOM_REPORT';
export const WEEKLY_REPORT_LOADING = 'WEEKLY_REPORT_LOADING';
export const CUSTOM_REPORT_LOADING = 'CUSTOM_REPORT_LOADING';


// Projects
export const  GET_PROJECTS ='GET_PROJECTS';
