export const GET_ERRORS = 'GET_ERRORS';

// Authentication
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USERS = 'GET_USERS';
export const CLEAR_USERS_FROM_STORE = 'CLEAR_USERS_FROM_STORE';




// Reports
export const CREATE_WEEKLY_REPORT = 'CREATE_WEEKLY_REPORT';
export const CREATE_CUSTOM_REPORT = 'CREATE_CUSTOM_REPORT';
export const GET_WEEKLY_REPORT = 'GET_WEEKLY_REPORT';
export const GET_CUSTOM_REPORT = 'GET_CUSTOM_REPORT';
export const GET_ALL_CUSTOM_REPORT = 'GET_ALL_CUSTOM_REPORT';
export const WEEKLY_REPORT_LOADING = 'WEEKLY_REPORT_LOADING';
export const CUSTOM_REPORT_LOADING = 'CUSTOM_REPORT_LOADING';
export const GET_VERIFING_CUSTOM_REPORTS = 'GET_VERIFING_CUSTOM_REPORTS';
export const VERIFING_CUSTOM_REPORTS_LOADING = 'VERIFING_CUSTOM_REPORTS_LOADING';
export const VERIFING_STATUS = 'VERIFING_STATUS';


// Projects
export const  GET_PROJECTS ='GET_PROJECTS';
export const  CREATE_PROJECTS ='CREATE_PROJECTS';
export const  PROJECT_CREATING ='PROJECT_CREATING';




